#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<MSG
Usage:
  ./clients/setup_clients_env.sh

Writes/updates `clients/.env` with:
  - CLIMAX_FUNCTIONS_URL
  - CLIMAX_FUNCTIONS_CODE (default function key)

Defaults:
  RG=rg-climax
  FUNCTION_APP=func-api-eedplxgcbbmra
  FUNCTIONS_URL=https://func-api-eedplxgcbbmra.azurewebsites.net

Override via env vars:
  CLIMAX_AZ_RESOURCE_GROUP
  CLIMAX_AZ_FUNCTION_APP
  CLIMAX_FUNCTIONS_URL

Requires:
  - Azure CLI (`az`) installed
  - `az login` already done (or otherwise authenticated)
MSG
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

if ! command -v az >/dev/null 2>&1; then
  echo "Missing az (Azure CLI)." >&2
  exit 1
fi

RG="${CLIMAX_AZ_RESOURCE_GROUP:-rg-climax}"
APP="${CLIMAX_AZ_FUNCTION_APP:-func-api-eedplxgcbbmra}"
URL_DEFAULT="https://func-api-eedplxgcbbmra.azurewebsites.net"
URL="${CLIMAX_FUNCTIONS_URL:-$URL_DEFAULT}"

# Verify access early (better error message than later curl failures)
if ! az account show >/dev/null 2>&1; then
  echo "Azure CLI is not logged in. Run: az login" >&2
  exit 1
fi

CODE="$(az functionapp keys list -g "$RG" -n "$APP" --query functionKeys.default -o tsv 2>/dev/null || true)"
if [ -z "$CODE" ]; then
  echo "Failed to fetch function key. Check RG/APP and your permissions:" >&2
  echo "  RG=$RG" >&2
  echo "  APP=$APP" >&2
  exit 1
fi

ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"
mkdir -p "$(dirname "$ENV_FILE")"

if [ -f "$ENV_FILE" ]; then
  cp -f "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
fi

tmp="$(mktemp)"
{
  echo "# Clients: shared Azure Functions endpoint"
  echo "# Auto-generated by clients/setup_clients_env.sh"
  echo
  echo "CLIMAX_FUNCTIONS_URL=\"$URL\""
  echo "CLIMAX_FUNCTIONS_CODE=\"$CODE\""
  echo
  echo "# Optional: override server_id used for session/log records (default: hostname)"
  echo "# CLIMAX_SERVER_ID=\"ubuntu-01\""
  echo
  echo "# Optional: default topic for command-unit logs (default: default)"
  echo "# CLIMAX_TOPIC=\"build\""
} >"$tmp"

mv -f "$tmp" "$ENV_FILE"

echo "Wrote: $ENV_FILE" >&2
echo "Next:" >&2
echo "  set -a; . clients/.env; set +a" >&2
